version: '3.7'

networks:
  laravel-net:
    external: true

volumes:
  mysqldata:
    driver: ${VOLUMES_DRIVER}
  redisdata:
    driver: ${VOLUMES_DRIVER}

services:
  # Laravel App
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args: 
        - PHP_VERSION=${PHP_VERSION}
    image: bmr333/laravel.app
    container_name: app
    tty: true
    restart: unless-stopped
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - "${NGINX_PHP_UPSTREAM_PORT}:9000"
    networks:
      - laravel-net
  
  # Nginx Service
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args: 
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
    image: bmr333/laravel.nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
    - "${NGINX_HOST_HTTP_PORT}:80"
    - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
      - mysql
    networks:
      - laravel-net
      
  # MySQL Service
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args: 
        - MYSQL_VERSION=${MYSQL_VERSION}
    image: bmr333/laravel.mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    networks:
      - laravel-net
    volumes:
      - mysqldata:/var/lib/mysql
      
  # Composer Service    
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    working_dir: ${APP_CODE_PATH_CONTAINER}
    depends_on:
      - app
    networks:
      - laravel-net
      
  # Node Service
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args: 
        - NODE_VERSION=${NODE_VERSION}
    image: bmr333/laravel.node
    container_name: node
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    networks:
      - laravel-net
  
  # Redis Service
  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
      args: 
        - REDIS_VERSION=${REDIS_VERSION}
    image: bmr333/laravel.redis
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - laravel-net
    volumes:
      - redisdata:/data